<a href="https://colab.research.google.com/github/Mayvon/exercicios-numpy/blob/main/04_numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios


1. Importe NumPy como `np`

In [ ]:
import numpy as np

2. Crie um array com 10 zeros

In [ ]:
array=np.zeros(10)
print("Um array com 10 zeros:")
print(array)

Um array com 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Crie um array com 10 'uns'

In [ ]:
array=np.ones(10)
print("Um array com 10 uns:")
print(array)

Um array com 10 uns:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


4. Crie um array com 10 'cincos'

In [ ]:
array=np.ones(10)*5
print("Um array com 10 cincos:")
print(array)

Um array com 10 cincos:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


5. Crie um vetor de números inteiros de 10 ate 50

In [ ]:
vetor =np.arange(10,51)
print("Vetor com números inteiros de 10 até 50:")
print(vetor)

Vetor com números inteiros de 10 até 50:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


6. Crie um vetor com o numeros pares de 10 até 50

In [ ]:
vetor =np.arange(10,51,2)
print("Vetor com números inteiros pares de 10 até 50:")
print(vetor)

Vetor com números inteiros pares de 10 até 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


7. Crie uma matriz $3 \times 3$ com os valores de 0 até 8

In [ ]:
matriz = np.arange(0,9).reshape((3, 3))
print('Matriz:')
print(matriz)

Matriz:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


8. Crie uma matriz identidade $7 \times 7$

In [ ]:
matriz =np.identity(7)
print('7x7 matriz:')
print(matriz)

7x7 matriz:
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


9. Use numpy para gerar um número aleatório entre 0 e 1

In [ ]:
aleatorio_1 = np.random.normal(0,1,1)
print("Número aleatório entre 0 e 1:")
print(aleatorio_1)

Número aleatório entre 0 e 1:
[1.15657643]


10. Use o numpy para gerar 25 números aleatório de distribuição normal padrão (gaussiana com média $\mu = 0$ e desvio padrão $\sigma = 1$)

In [ ]:
num_aleatorios = np.random.normal(0,1,25)
print("25 númeors aleatórios em distribuição normal padrão:")
print(num_aleatorios)

25 númeors aleatórios em distribuição normal padrão:
[-0.04316391  0.99317491  0.35959441 -0.0734801   1.10464305 -0.48345925
 -0.97388433 -0.66331991  1.89343734  0.07779155  1.017227   -1.00514526
 -0.76717918  0.46009702 -0.38981832 -1.06698686 -0.4178041  -1.01110852
 -1.29062181  0.55671796 -0.56581382  0.17416906  2.26825494 -0.9743419
  1.53091768]


11. Crie a matrix abaixo

```python
array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])
```

In [ ]:

np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

12. Crie um array de 20 elementos igulmente espaçados entre 0 e 1:

In [ ]:
array = np.linspace(0, 1, 20)
print(array)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


13. Dada a matrix abaixo,

```python
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

obtenha as seguintes matrizes por indexação e se necessário, reshape:
*
```python
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```
*
```python
array([[ 2],
       [ 7],
       [12]])
```
*
```python
array([21, 22, 23, 24, 25])
```
*
```python
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

In [ ]:
import numpy as np
matriz = np.arange(1,26).reshape(5,5)
print(matriz)


#Tentar fazer ainda hoje!

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


14. Some todos os valores da matriz

In [ ]:
matriz.sum()

325

15. Some todas as colunas da matriz

In [ ]:
print('A soma de todas as colunas é:')
matriz.sum(axis=0)

A soma de todas as colunas é:


array([55, 60, 65, 70, 75])

16. Calcule o desvio padrão por coluna

In [ ]:
print('O desvio padrão por coluna é:')
matriz.std(axis=0)

O desvio padrão por coluna é:


array([0.34992711, 0.34992711, 0.34992711, 0.34992711, 0.34992711,
       0.34992711, 0.34992711])